#!/bin/bash

. $TFS_HOME/conf/registry;
VERSION=${VERSION:-"latest"};

if [ $# -lt 1 ]; then
    Usage;
fi

# 启动容器
function start_docker {
    sudo docker start tfs-registry;
    sudo pipework docker0 tfs-myql $IP/$MASK@$GATEWAY;
}

# 停止容器
function stop_docker {
    sudo docker stop tfs-registry;
}

# 创建并初始化+启动容器
function run_docker {
    sudo docker run -i -t -d --hostname=tfs-registry --name=tfs-registry \
    -v $HOME/appstore/tfs/registry/images:/opt/docker-image \
    -e DOCKER_REGISTRY_CONFIG=/opt/docker-image/registry-config/config.yml
    registry:$VERSION

    sudo pipework docker0 tfs-registry $IP/$MASK@$GATEWAY;
}

#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

   clean) echo "clean completed" ;;
esac 


# 启动

