#!/bin/bash

. $TFS_HOME/conf/memcached;
VERSION=${VERSION:-"latest"}

if [ $# -lt 1 ]; then
    echo "tfs-memcached run|start|stop|clean";
    exit 0;
fi

# 创建+初始化+启动
function run_docker {
    sudo docker run -i -t -d --name tfs-memcached --hostname tfs-memcached hary/memcached:$VERSION;
    sudo pipework docker0 tfs-memcached $IP/$MASK@$GATEWAY;
}

# 启动
function start_docker {
    sudo docker start tfs-memcached;
    sudo pipework docker0 tfs-memcached $IP/$MASK@$GATEWAY;
}

# 停止
function stop_docker {
    sudo docker stop tfs-memcached;
}

#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

   clean) echo "clean completed";;
esac

