#!/bin/bash

. $TFS_HOME/conf/mysql
VERSION=${VERSION:-"latest"};

# 启动
function start_docker {
    sudo docker start tfs-mysql;
    sudo pipework docker0 tfs-myql $IP/$MASK@$GATEWAY;
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]";
}

# 停止容器
function stop_docker {
    sudo docker stop_docker tfs-mysql;
}

# 创建并初始化+启动容器
function run_docker {
    echo "run docker using image[hary/mysql] version[$VERSION]";
    sudo docker run -i -t -d --hostname=tfs-mysql --name=tfs-mysql \
    -e "DB_NAME=$DB_NAME" \
    -e "DB_USER=$DB_USER" \
    -e "DB_PASS=$DB_PASS" \
    -v $VOLUME_DATA:/var/lib/mysql \
    hary/mysql:$VERSION;

    # IP地址设置
    sudo pipework docker0 tfs-mysql $IP/$MASK@$GATEWAY;
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]";
}


#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

   # clean volume data
   clean) sudo rm -fr $VOLUME_DATA/*;;
esac 


