#!/bin/bash

. $TFS_HOME/conf/jenkins;
VERSION=${VERSION:-"latest"}

# rest parameters
if [ $# -lt 1 ]; then
    Usage;
fi

# 启动容器
function start_docker {
    sudo docker start tfs-jenkins;
    sudo pipework docker0 tfs-jenkins $IP/$MASK@$GATEWAY
}

# 停止容器
function stop_docker {
    sudo docker stop tfs-jenkins;
}

# 创建+初始化+启动容器
function run_docker {
    sudo docker run -i -t --rm \
    --name=tfs-jenkins \
    --hostname=tfs-jenkins \
    --link tfs-mysql:mysql \
    -e "DB_NAME=$DB_NAME" \
    -e "DB_USER=$DB_USER" \
    -e "DB_PASS=$DB_PASS" \
    -v $VOLUME_DATA:/home/jenkins/opt/jenkins/data \
    -v $VOLUME_LOG:/home/jenkins/opt/jenkins/logs \
    -v $VOLUME_TEMP:/home/jenkins/opt/jenkins/temp \
    hary/jenkins:$VERSION

    # 设置容器地址
    pipework docker0 tfs-jenkins $IP/$MASK@$GATEWAY
}


#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

   clean) echo "clean completed";;
esac


