#!/bin/bash

# mirror of ubuntu 14.04 and centos 6.6,7.0

. $TFS_HOME/conf/mirror;
VERSION=${VERSION:-"latest"};

if [ $# -lt 1 ]; then
    Usage;
fi

# 创建+初始化+启动
function run_docker {
    sudo docker run -i -t -d --name tfs-mirror --hostname tfs-mirror sameersbn/mirror:$VERSION;
    sudo pipework docker0 tfs-mirror $IP/$MASK@$GATEWAY;
}

# 启动
function start_docker {
    sudo docker start tfs-mirror;
    sudo pipework docker0 tfs-mirror $IP/$MASK@$GATEWAY;
}

# 停止
function stop_docker {
    sudo docker start tfs-mirror;
}


#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

   clean) echo "clean completed";;
esac

