#!/bin/bash

. $TFS_HOME/conf/redmine
VERSION=${VERSION:-"latest"};

# 启动容器
function start_docker {
    sudo docker start tfs-archiva;
    sudo pipework docker0 tfs-redmine $IP/$MASK@$GATEWAY
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]";
}

# 停止容器
function stop_docker {
    sudo docker stop tfs-redmine;
}

# 创建容器+初始化+启动容器
function run_docker {
    sudo docker run -i -t -d --name tfs-redmine --hostname tfs-redmine \
    -e "SMTP_USER=$SMTP_USER" \
    -e "SMTP_PASS=$SMTP_PASS" \
    -e "SMTP_HOST=$SMTP_HOST" \
    -e "SMTP_PORT=$SMTP_PORT" \
    -v $VOLUME_DATA:/home/redmine/data \
    -v $VOLUME_LOG:/var/log/redmine \
    --link tfs-mysql:mysql \
    -e "DB_NAME=$DB_NAME" \
    -e "DB_USER=$DB_USER" \
    -e "DB_PASS=$DB_PASS" \
    hary/redmine:$VERSION

    # 添加IP地址
    sudo pipework docker0 tfs-redmine $IP/$MASK@$GATEWAY;
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]";
}

#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

   # clean volume data
   clean) sudo rm -fr $VOLUME_DATA/* $VOLUME_LOG/* ;;
esac

