#!/bin/bash

. $TFS_HOME/conf/pgsql;
VERSION=${VERSION:-"latest"};

if [ $# -lt 1 ]; then
    Usage;
fi


# 从容器启动
function start_docker {
    echo "start docker[tfs-pgsql]...";
    sudo docker start tfs-pgsql;
    sudo pipework docker0 tfs-pgsql $IP/$MASK@$GATEWAY
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]"
}

# 停止容器
function stop_docker {
    sudo docker stop tfs-pgsql;
}

# 创建容器+初始化+启动
function run_docker {
    echo "run docker using image[hary/postgresql] version[$VERSION]";
    sudo docker run -i -t -d --name tfs-pgsql --hostname tfs-pgsql \
    -e "DB_USER=$DB_USER" \
    -e "DB_PASS=$DB_PASS" \
    -e "DB_NAME=$DB_NAME" \
    -v $VOLUME_DATA:/var/lib/postgresql \
    hary/postgresql:$VERSION

    # 设置IP地址
    sudo pipework docker0 tfs-pgsql $IP/$MASK@$GATEWAY;
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]"
}

#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

   # clean volume data
   clean) sudo rm -fr $VOLUME_DATA/*;;
esac

