#!/bin/bash

. $TFS_HOME/conf/redis
VERSION=${VERSION:-"latest"};

if [ $# -lt 1 ]; then
    Usage;
fi


# 创建+初始化+启动
function run_docker {
    echo "run docker using image[hary/redis] version[$VERSION]";
    sudo docker run -i -t -d --name tfs-redis --hostname tfs-redis hary/redis:$VERSION;
    sudo pipework docker0 tfs-redis $IP/$MASK@$GATEWAY;
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]";
}

# 启动
function start_docker {
    sudo docker start tfs-redis;
    sudo pipework docker0 tfs-redis $IP/$MASK@$GATEWAY;
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]";
}

# 停止
function stop_docker {
    sudo docker stop tfs-redis;
}

#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

   clean) echo "clean completed";;
esac


